server:
  port: 8443
  servlet:
    context-path: /healthcheck

app:
  config:
    health-check-report:
      endpoint: https://hiring-challenge.appspot.com/healthcheck/report
    line:
      access-token: ${access_token}
